#Frobenius Norm

In [ ]:
# menggunakan numpy, pytoch dan tensorflow buatlah matrix ukuran 3x3 lalu hitung nilai frobenius norm
import numpy as np

In [ ]:
X = np.array([[92, 29, 10], [11, 40, 55], [17, 33, 22]])
X

array([[92, 29, 10],
       [11, 40, 55],
       [17, 33, 22]])

In [ ]:
(92**2 + 29**2 + 10**2 + 11**2 + 40**2 + 55**2 + 17**2 + 33**2 + 22**2)**(1/2)

126.54248298496438

In [ ]:
np.linalg.norm(X)

np.float64(126.54248298496438)

# Pytorch

In [ ]:
import torch

In [ ]:
X_pt = torch.tensor([[92, 29, 10], [11, 40, 55], [17, 33, 22]])

In [ ]:
torch.tensor(X_pt)

/tmp/ipykernel_1169/2903562501.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  torch.tensor(X_pt)


tensor([[92, 29, 10],
        [11, 40, 55],
        [17, 33, 22]])

#Tensorflow

In [ ]:
import tensorflow as tf


In [ ]:
X_tf = tf.Variable([[92, 29, 10], [11, 40, 55], [17, 33, 22]])

In [ ]:
tf.Variable(X_tf)

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[92, 29, 10],
       [11, 40, 55],
       [17, 33, 22]], dtype=int32)>