In [9]:
#buat matrix X ukuran 2x2 menggunakan numpy
import numpy as np
X = np.array([[1, 2], [3, 4]])
print(X)

[[1 2]
 [3 4]]


In [10]:
#buat invers dari matrix X dan beri nama Xinv menggunakan numpy
Xinv = np.linalg.inv(X)
Xinv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [11]:
#kalikan X dengan Xinv menggunakan numpy
np.dot(Xinv, X)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [13]:
import numpy as np
import tensorflow as tf
import torch

print("=== PENYELESAIAN DENGAN NUMPY ===")
# 1. Mendefinisikan matriks A dan y (y dibuat sebagai matriks kolom)
A_np = np.array([[4, 2],
                 [-5, -3]])
y_np = np.array([[4],
                 [-7]])

# 2. Mencari invers dari matriks A
A_inv_np = np.linalg.inv(A_np)

# 3. Mengalikan invers A dengan y (A_inv * y)
hasil_np = np.matmul(A_inv_np, y_np) # Bisa juga menggunakan A_inv_np.dot(y_np)

print("Invers Matriks A (NumPy):\n", A_inv_np)
print(f"Hasil: b = {hasil_np[0][0]:.0f}, c = {hasil_np[1][0]:.0f}\n")


print("=== PENYELESAIAN DENGAN TENSORFLOW ===")
# 1. Mendefinisikan tensor (harus float untuk operasi inversi)
A_tf = tf.constant([[4.0, 2.0],
                    [-5.0, -3.0]])
y_tf = tf.constant([[4.0],
                    [-7.0]])

# 2. Mencari invers dari matriks A
A_inv_tf = tf.linalg.inv(A_tf)

# 3. Mengalikan invers A dengan y
hasil_tf = tf.matmul(A_inv_tf, y_tf)

print("Invers Matriks A (TensorFlow):\n", A_inv_tf.numpy())
print(f"Hasil: b = {hasil_tf[0][0]:.0f}, c = {hasil_tf[1][0]:.0f}\n")


print("=== PENYELESAIAN DENGAN PYTORCH ===")
# 1. Mendefinisikan tensor di PyTorch (harus float)
A_pt = torch.tensor([[4.0, 2.0],
                     [-5.0, -3.0]])
y_pt = torch.tensor([[4.0],
                     [-7.0]])

# 2. Mencari invers dari matriks A
A_inv_pt = torch.inverse(A_pt) # atau torch.linalg.inv(A_pt)

# 3. Mengalikan invers A dengan y
hasil_pt = torch.matmul(A_inv_pt, y_pt)

print("Invers Matriks A (PyTorch):\n", A_inv_pt.numpy())
print(f"Hasil: b = {hasil_pt[0][0]:.0f}, c = {hasil_pt[1][0]:.0f}")

=== PENYELESAIAN DENGAN NUMPY ===
Invers Matriks A (NumPy):
 [[ 1.5  1. ]
 [-2.5 -2. ]]
Hasil: b = -1, c = 4

=== PENYELESAIAN DENGAN TENSORFLOW ===
Invers Matriks A (TensorFlow):
 [[ 1.4999998  0.9999998]
 [-2.4999995 -1.9999996]]
Hasil: b = -1, c = 4

=== PENYELESAIAN DENGAN PYTORCH ===
Invers Matriks A (PyTorch):
 [[ 1.5  1. ]
 [-2.5 -2. ]]
Hasil: b = -1, c = 4
