# Matrix Multiplication Exercises

In [ ]:
# lakukan perhitungan soal excercise menggunakan collab

## soal 1

In [2]:
import numpy as np

In [3]:
A = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
b = np.array([[-1],
              [1],
              [-2]])
b

array([[-1],
       [ 1],
       [-2]])

In [5]:
np.dot(A, b)

array([[ -3],
       [ -9],
       [-15]])

In [6]:
import torch

In [8]:
A_pt = torch.tensor([[0, 1, 2],
                     [3, 4, 5],
                     [6, 7, 8]])
A_pt

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [9]:
b_pt = torch.tensor([[-1],
                     [1],
                     [-2]])
b_pt

tensor([[-1],
        [ 1],
        [-2]])

In [10]:
torch.matmul(A_pt, b_pt)

tensor([[ -3],
        [ -9],
        [-15]])

In [7]:
import tensorflow as tf

In [11]:
A_tf = tf.Variable([[0, 1, 2],
                    [3, 4, 5],
                    [6, 7, 8]])
A_tf

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)>

In [12]:
b_tf = tf.Variable([[-1],
                    [1],
                    [-2]])
b_tf

<tf.Variable 'Variable:0' shape=(3, 1) dtype=int32, numpy=
array([[-1],
       [ 1],
       [-2]], dtype=int32)>

In [13]:
tf.linalg.matmul(A_tf, b_tf)

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[ -3],
       [ -9],
       [-15]], dtype=int32)>

## soal 2

In [32]:
A = np.array([[1, 0, 0],
              [0, 1, 0],
              [0, 0, 1]])
b = np.array([[-1], [1], [-2]])

In [18]:
np.dot(A, b)

array([[-1],
       [ 1],
       [-2]])

In [25]:
A_pt = torch.tensor([[1, 0, 0],
                    [0, 1, 0],
                    [0, 0, 1]])
b_pt = torch.tensor([[-1], [1], [-2]])

In [26]:
torch.matmul(A_pt, b_pt)

tensor([[-1],
        [ 1],
        [-2]])

In [30]:
A_tf = tf.Variable([[1, 0, 0],
                    [0, 1, 0],
                    [0, 0, 1]])
b_tf = tf.Variable([[-1], [1], [-2]])

In [31]:
tf.linalg.matmul(A_tf, b_tf)

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[-1],
       [ 1],
       [-2]], dtype=int32)>

## soal 3

In [33]:
A = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])

B = np.array([[-1, 0],
              [1, 1],
              [-2, 2]])

In [34]:
np.dot(A, B)

array([[ -3,   5],
       [ -9,  14],
       [-15,  23]])

In [36]:
A_pt = torch.tensor([[0, 1, 2],
                     [3, 4, 5],
                     [6, 7, 8]])

B_pt = torch.tensor([[-1, 0],
                     [1, 1],
                     [-2, 2]])

In [37]:
torch.matmul(A_pt, B_pt)

tensor([[ -3,   5],
        [ -9,  14],
        [-15,  23]])

In [38]:
A_tf = tf.Variable([[0, 1, 2],
                    [3, 4, 5],
                    [6, 7, 8]])

B_tf = tf.Variable([[-1, 0],
                    [1, 1],
                    [-2, 2]])

In [39]:
tf.linalg.matmul(A_tf, B_tf)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ -3,   5],
       [ -9,  14],
       [-15,  23]], dtype=int32)>