# Matrix Multiplication

In [ ]:
import numpy as np

In [ ]:
# buat matrix A dengan ukuran 2x3 dan vector b berukuran 3x1 menggunakan numpy
A = np.array([[2, 5, 1], [5, 6, 1],])
A

array([[2, 5, 1],
       [5, 6, 1]])

In [ ]:
b = np.array([[6],
              [1],
              [4]])
b

array([[6],
       [1],
       [4]])

In [ ]:
import torch

In [ ]:
# buat matrix A_pt dengan ukuran 2x3 dan vector b_pt berukuran 3x1 menggunakan pytorch
A_pt = torch.tensor([[1, 5, 6], [1, 4, 2]])
A_pt

tensor([[1, 5, 6],
        [1, 4, 2]])

In [ ]:
b_pt = torch.tensor([[2],
                     [4],
                     [1]])
b_pt

tensor([[2],
        [4],
        [1]])

In [ ]:
import tensorflow as tf

In [ ]:
# buat matrix A_tf dengan ukuran 2x3 dan vector b_tf berukuran 3x1 menggunakan tensorflow
A_tf = tf.Variable([[1, 2, 3], [4, 5, 6]])
A_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
b_tf = tf.Variable([[7],
                    [8],
                    [9]])
b_tf

<tf.Variable 'Variable:0' shape=(3, 1) dtype=int32, numpy=
array([[7],
       [8],
       [9]], dtype=int32)>

In [ ]:
# tampilkan ukuran matrix A dan vector b
X = A.shape
X

(2, 3)

In [ ]:
X = b.shape
X

(3, 1)

In [ ]:
# kalikan matrix A dengan vector b
np.dot (A, b)

array([[21],
       [40]])

In [ ]:
# kalikan matrix A_pt dengan vector b_pt
torch.matmul(A_pt, b_pt)

tensor([[28],
        [20]])

In [ ]:
# kalikan matrix A_tf dengan vector b_tf
tf.linalg.matvec(A_tf, tf.squeeze(b_tf))

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 50, 122], dtype=int32)>

In [ ]:
# buat matrix B dengan ukuran 3x3 menggunakan numpy
B = np.array([[2, 5, 1], [5, 6, 1], [4, 0, 9]])
B

array([[2, 5, 1],
       [5, 6, 1],
       [4, 0, 9]])

In [ ]:
# buat matrix B_pt dengan ukuran 3x3 menggunakan pytorch
B_pt = torch.tensor([[2, 5, 1], [5, 6, 1], [4, 0, 9]])
B_pt

tensor([[2, 5, 1],
        [5, 6, 1],
        [4, 0, 9]])

In [ ]:
# buat matrix B_tf dengan ukuran 3x3 menggunakan tensorflow
B_tf = tf.Variable([[2, 5, 1], [5, 6, 1], [4, 0, 9]])
B_tf

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[2, 5, 1],
       [5, 6, 1],
       [4, 0, 9]], dtype=int32)>

In [ ]:
# kalikan matrix A dengan matrix B
np.dot(A, B)

array([[33, 40, 16],
       [44, 61, 20]])

In [ ]:
# kalikan matrix A_pt dengan matrix B_pt
torch.matmul(A_pt, B_pt)

tensor([[51, 35, 60],
        [30, 29, 23]])

In [ ]:
# kalikan matrix A_tf dengan matrix B_tf
tf.linalg.matmul(A_tf, B_tf)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[24, 17, 30],
       [57, 50, 63]], dtype=int32)>

In [ ]:
# buktikan apakah perkalian matrix bersifat komutatif? (AB=BA)?
# np.dot(B, A)

In [ ]:
B_pt = torch.from_numpy(B)
B_pt

tensor([[2, 5, 1],
        [5, 6, 1],
        [4, 0, 9]])

In [ ]:
B_pt = torch.tensor([[2, 5, 1], [5, 6, 1], [4, 0, 9]]).T
B_pt

tensor([[2, 5, 4],
        [5, 6, 0],
        [1, 1, 9]])

In [ ]:
torch.matmul(A_pt, B_pt)

tensor([[33, 41, 58],
        [24, 31, 22]])

In [ ]:
B_tf = tf.convert_to_tensor(B, dtype=tf.int32)
B_tf

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[2, 5, 1],
       [5, 6, 1],
       [4, 0, 9]], dtype=int32)>

In [ ]:
tf.matmul(A_tf, B_tf)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[24, 17, 30],
       [57, 50, 63]], dtype=int32)>