In [27]:
import numpy as np
import torch
import tensorflow as tf

In [28]:
#1.buat matrix X dengan ukuran 2x3 menggunakan numpy
X = np.array ([[1, 2, 3], [4, 5, 6]])
print(f"berikut matrix X dengan ukuran 2x3 menggunakan numpy {X}")


berikut matrix X dengan ukuran 2x3 menggunakan numpy [[1 2 3]
 [4 5 6]]


In [29]:
#buat matrix X_pt dengan ukuran 2x3 menggunakan pytorch
X_pt = torch.tensor ([[1, 2, 3], [4, 5, 6]])
print(f"berikut matrix X_pt dengan ukuran 2x3 menggunakan pytorch {X_pt}")


berikut matrix X_pt dengan ukuran 2x3 menggunakan pytorch tensor([[1, 2, 3],
        [4, 5, 6]])


In [30]:
#buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflow
X_tf = tf.Variable ([[1, 2, 3], [4, 5, 6]])
print(f"berikut matrix X_tf dengan ukuran 2x3 menggunakan tensorflow{X_tf} ")

berikut matrix X_tf dengan ukuran 2x3 menggunakan tensorflow<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)> 


In [44]:
#lakukan perkalian matrix X, X_pt dan X_tf dengan suatu skalar
#X
X*2
#X_pt
X_pt*2
#X_tf
X_tf*2
print(f"hasil perkalian X dengan skalar {X*2}")
print(f"hasil perkalian X_pt dengan skalar {X_pt*2}")
print(f"hasil perkalian X_tf dengan skalar {X_tf*2}")


hasil perkalian X dengan skalar [[ 2  4  6]
 [ 8 10 12]]
hasil perkalian X_pt dengan skalar tensor([[ 2,  4,  6],
        [ 8, 10, 12]])
hasil perkalian X_tf dengan skalar [[ 2  4  6]
 [ 8 10 12]]


In [45]:
#lakukan penjumlahan matrix X, X_pt dan X_tf dengan suatu skalar
#X
X+2
#X_pt
X_pt+2
#X_tf
X_tf+2
print(f"hasil penjumlahan X dengan skalar {X+2}")
print(f"hasil penjumlahan X_pt dengan skalar {X_pt+2}")
print
print(f"hasil penjumlahan X_tf dengan skalar {X_tf+2}")

hasil penjumlahan X dengan skalar [[3 4 5]
 [6 7 8]]
hasil penjumlahan X_pt dengan skalar tensor([[3, 4, 5],
        [6, 7, 8]])
hasil penjumlahan X_tf dengan skalar [[3 4 5]
 [6 7 8]]


In [57]:
#lakukan pengurangan matrix X, X_pt dan X_tf dengan suatu skalar
#X
A=X-2
#X_pt
B=X_pt-2
#X_tf-2
C=X_tf-2
print(f"hasil pengurangan X dengan skalar {A}")
print(f"hasil pengurangan X_pt dengan skalar {B}")
print(f"hasil pengurangan X_tf dengan skalar {C}")

hasil pengurangan X dengan skalar [[-1  0  1]
 [ 2  3  4]]
hasil pengurangan X_pt dengan skalar tensor([[-1,  0,  1],
        [ 2,  3,  4]])
hasil pengurangan X_tf dengan skalar [[-1  0  1]
 [ 2  3  4]]


In [48]:
#2.buat matrix Y dengan ukuran 2x3 menggunakan numpy
Y = np.array ([[7, 8, 9], [10, 11, 12]])
print(f"berikut matrix Y dengan ukuran 2x3 menggunakan numpy {Y}")

berikut matrix Y dengan ukuran 2x3 menggunakan numpy [[ 7  8  9]
 [10 11 12]]


In [50]:
#buat matrix Y_pt dengan ukuran 2x3 menggunakan pytorch
Y_pt = torch.tensor ([[7, 8, 9], [10, 11, 12]])
print(f"berikut matrix Y_pt dengan ukuran 2x3 menggunakan pytorch {Y_pt}")

berikut matrix Y_pt dengan ukuran 2x3 menggunakan pytorch tensor([[ 7,  8,  9],
        [10, 11, 12]])


In [52]:
#buat matrix Y_tf dengan ukuran 2x3 menggunakan tensorflow
Y_tf = tf.Variable ([[7, 8, 9], [10, 11, 12]])
print(f"berikut matrix Y_tf dengan ukuran 2x3 menggunakan tensorflow {Y_tf}")


berikut matrix Y_tf dengan ukuran 2x3 menggunakan tensorflow <tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>


In [59]:
#kalikan matrix X dengan Y
A = X*Y
print(f"hasil perkalian matrix X dengan Y {A}")

hasil perkalian matrix X dengan Y [[ 7 16 27]
 [40 55 72]]


In [60]:
#kalikan matrix X_pt dengan Y_pt
B=X_pt*Y_pt
print(f"hasil perkalian matrix X_pt dengan Y_pt {X_pt*Y_pt}")

hasil perkalian matrix X_pt dengan Y_pt tensor([[ 7, 16, 27],
        [40, 55, 72]])


In [61]:
#kalikan matrix X_tf dengan Y_tf
C=X_tf*Y_tf
print(f"hasil perkalian matrix X_tf dengan Y_tf {X_tf*Y_tf}")


hasil perkalian matrix X_tf dengan Y_tf [[ 7 16 27]
 [40 55 72]]
