# Tensor Transposition

In [ ]:
# buat matrix X dengan ukuran 2x3 menggunakan numpy
import numpy as np
import torch
import tensorflow as tf

In [ ]:
X = np.array([[29, 92, 85], [96, 93, 79]])
X

array([[29, 92, 85],
       [96, 93, 79]])

In [ ]:
X.T

array([[29, 96],
       [92, 93],
       [85, 79]])

# Using Torch

In [ ]:
# buat matrix X_pt dengan ukuran 2x3 menggunakan pytorch
X_pt = torch.tensor([[29, 92, 85], [96, 93, 79]])
X_pt

tensor([[29, 92, 85],
        [96, 93, 79]])

In [ ]:
X_pt.T

tensor([[29, 96],
        [92, 93],
        [85, 79]])

# Using Tensorflow

In [ ]:
# buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflow
X_tf = tf.Variable([[29, 92, 85], [96, 93, 79]])
X_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[29, 92, 85],
       [96, 93, 79]], dtype=int32)>

In [ ]:
tf.transpose(X_tf)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[29, 96],
       [92, 93],
       [85, 79]], dtype=int32)>