In [ ]:
import numpy as np

In [ ]:
# buat matrix X dengan ukuran 2x3 menggunakan numpy
X = np.array([
    [104, 25, 89],
    [34, 20, 50],
])
print('='*10+' Matrix 2x3 '+'='*10)
print(f'X = {X}')
print('='*32)

========== Matrix 2x3 ==========
X = [[104  25  89]
 [ 34  20  50]]


In [ ]:
# hitung berapa hasil penjumlahan elemen matrix X dengan fungsi sum
X_sum = X.sum()
print('='*5+' Hasil Penjumlahan Elemen Matrix '+'='*5)
print(f'X_sum = {X_sum}')
print('='*43)

===== Hasil Penjumlahan Elemen Matrix =====
X_sum = 322


In [ ]:
import torch

In [ ]:
X_pt = torch.tensor(
    [
    [12, 51, 77],
    [78, 11, 15],
]
)
print('='*10+' Matrix 2x3 '+'='*10)
print(f'X_pt = {X_pt}')
print('='*32)

========== Matrix 2x3 ==========
X_pt = tensor([[12, 51, 77],
        [78, 11, 15]])


In [ ]:
import tensorflow as tf

In [ ]:
# buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflow
X_tf = tf.Variable([
    [54, 25, 22],
    [78, 40, 32],
])
print('='*10+' Matrix 2x3 '+'='*10)
print(f'X_tf = {X_tf}')
print('='*32)

========== Matrix 2x3 ==========
X_tf = <tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[54, 25, 22],
       [78, 40, 32]], dtype=int32)>


In [ ]:
# hitung hasil penjumlahan seluruh elemen matrix X
X_sum_2 = X.sum()
print('='*5+' Hasil Penjumlahan Elemen Matrix '+'='*5)
print(f'X_sum_2 = {X_sum_2}')
print('='*43)

===== Hasil Penjumlahan Elemen Matrix =====
X_sum_2 = 322


In [ ]:
# hitung hasil penjumlahan seluruh elemen matrix X_pt
X_pt_sum = torch.sum(X_pt)
print('='*5+' Hasil Penjumlahan Elemen Matrix '+'='*5)
print(f'X_pt_sum = {X_pt_sum}')
print('='*43)

===== Hasil Penjumlahan Elemen Matrix =====
X_pt_sum = 244


In [ ]:
# hitung hasil penjumlahan seluruh elemen matrix X_tf
X_tf_sum = tf.reduce_sum(X_tf)
print('='*5+' Hasil Penjumlahan Elemen Matrix '+'='*5)
print(f'X_tf_sum = {X_tf_sum}')
print('='*43)

===== Hasil Penjumlahan Elemen Matrix =====
X_tf_sum = 251


In [ ]:
# hitung hasil penjumlahan matrix X berdasarkan row nya
X_row_sum = X.sum(axis=0)
print('='*5+' Hasil Penjumlahan Elemen Matrix '+'='*5)
print(f'X_row_sum = {X_row_sum}')
print('='*43)

===== Hasil Penjumlahan Elemen Matrix =====
X_row_sum = [138  45 139]


In [ ]:
# hitung hasil penjumlahan matrix X_pt berdasarkan row nya
X_pt_row = torch.sum(X_pt, axis=0)
print('='*5+' Hasil Penjumlahan Elemen Matrix '+'='*5)
print(f'X_pt_row = {X_pt_row}')
print('='*43)

===== Hasil Penjumlahan Elemen Matrix =====
X_pt_row = tensor([90, 62, 92])


In [ ]:
# hitung hasil penjumlahan matrix X_tf berdasarkan row nya
Xtf_sum = tf.reduce_sum(X_tf, axis=0)
print('='*5+' Hasil Penjumlahan Elemen Matrix '+'='*5)
print(f'Xtf_sum = {Xtf_sum}')
print('='*43)

===== Hasil Penjumlahan Elemen Matrix =====
Xtf_sum = [132  65  54]


In [ ]:
# hitung hasil penjumlahan matrix X berdasarkan kolom nya
X_sum_col = X.sum(axis=1)
print('='*5+' Hasil Penjumlahan Elemen Matrix '+'='*5)
print(f'X_sum_col = {X_sum_col}')
print('='*43)

===== Hasil Penjumlahan Elemen Matrix =====
X_sum_col = [218 104]


In [ ]:
# hitung hasil penjumlahan matrix X_pt berdasarkan kolom nya
X_torch_col = torch.sum(X_pt, axis=1)
print('='*5+' Hasil Penjumlahan Elemen Matrix '+'='*5)
print(f'X_torch_col = {X_torch_col}')
print('='*43)

===== Hasil Penjumlahan Elemen Matrix =====
X_torch_col = tensor([140, 104])


In [ ]:
# hitung hasil penjumlahan matrix X_tf berdasarkan kolom nya
tf.reduce_sum(X_tf, axis=1)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([101, 150], dtype=int32)>

In [ ]:
# hitung nilai minimal dari matrix X, X_pt dan X_tf
X_min = X.min()
X_pt_min = X_pt.min()
X_tf_min = tf.reduce_min(X_tf)

print(f"Nilai minimal dari matrix X (Numpy): {X_min}")
print(f"Nilai minimal dari matrix X_pt (PyTorch): {X_pt_min}")
print(f"Nilai minimal dari matrix X_tf (Tensorflow): {X_tf_min}")

Nilai minimal dari matrix X (Numpy): 20
Nilai minimal dari matrix X_pt (PyTorch): 11
Nilai minimal dari matrix X_tf (Tensorflow): 22


In [ ]:
# hitung nilai maksimal dari matrix X, X_pt dan X_tf
X_max = X.max()
X_pt_max = X_pt.max()
X_tf_max = tf.reduce_max(X_tf)

print("Nilai maksimal dari X (NumPy):", X_max)
print("Nilai maksimal dari X_pt (PyTorch):", X_pt_max)
print("Nilai maksimal dari X_tf (Tensorflow):", X_tf_max)


Nilai maksimal dari X (NumPy): 104
Nilai maksimal dari X_pt (PyTorch): tensor(78)
Nilai maksimal dari X_tf (Tensorflow): tf.Tensor(78, shape=(), dtype=int32)


In [ ]:
# hitung nilai rata-rata dari matrix X, X_pt dan X_tf
X_mean = X.mean()
X_pt_mean = X_pt.float().mean()
X_tf_mean = tf.reduce_mean(X_tf)

print("Nilai rata-rata dari X (NumPy):", X_mean)
print("Nilai rata-rata dari X_pt (PyTorch):", X_pt_mean)
print("Nilai rata-rata dari X_tf (Tensorflow):", X_tf_mean)

Nilai rata-rata dari X (NumPy): 53.666666666666664
Nilai rata-rata dari X_pt (PyTorch): tensor(40.6667)
Nilai rata-rata dari X_tf (Tensorflow): tf.Tensor(41, shape=(), dtype=int32)


In [ ]:
# hitung hasil perkalian seluruh elemen matrix X
X_prod = X.prod()
print("Hasil perkalian seluruh elemen matrix X (NumPy):", X_prod)

Hasil perkalian seluruh elemen matrix X (NumPy): 7867600000


In [ ]:
# hitung hasil perkalian seluruh elemen matrix X_pt
X_pt_prod = X_pt.prod()
print("Hasil perkalian seluruh elemen matrix X_pt (PyTorch):", X_pt_prod)

Hasil perkalian seluruh elemen matrix X_pt (PyTorch): tensor(606485880)


In [ ]:
# hitung hasil perkalian seluruh elemen matrix X_tf
X_tf_prod = tf.reduce_prod(X_tf)
print("Hasil perkalian seluruh elemen matrix X_tf (Tensorflow):", X_tf_prod)

Hasil perkalian seluruh elemen matrix X_tf (Tensorflow): tf.Tensor(-1329719296, shape=(), dtype=int32)
